version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yarn install

  build:
    commands:
      - yarn build
      # Package the Lambda functio
      - mkdir -p output
      - cp -r node_modules output/
      - cp -r index.js output/
      - cd output
      - zip -r ../output.zip .
      - cd ..

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Deploying to AWS Lambda"
      # Replace `my-lambda-function` with your Lambda function name
      - aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://output.zip

artifacts:
  files:
    - output.zip
