version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  pre_build:
    commands:
      - echo Preparing to run
  build:
    commands:
      - echo No build step needed
  post_build:
    commands:
      - echo Build and deployment completed

artifacts:
  files:
    - '**/*'
